services:
  db:
    image: supabase/postgres:15.1.1.78
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - coolify

  auth:
    image: supabase/gotrue:v2.132.3
    environment:
      GOTRUE_DB_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres?sslmode=disable&prepared_statements=false
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_SITE_URL: https://nodes-tracker.ru
      GOTRUE_API_EXTERNAL_URL: https://db.nodes-tracker.ru/auth/v1
      API_EXTERNAL_URL: https://db.nodes-tracker.ru/auth/v1
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_EXTERNAL_GOOGLE_ENABLED: "true"
      GOTRUE_DB_PREPARED_STATEMENTS: "false"
      DB_PREPARED_STATEMENTS: "false"
      # DB Settings
      GOTRUE_DB_MAX_POOL_SIZE: 20
    networks:
      - coolify

  rest:
    image: postgrest/postgrest:v11.2.2
    environment:
      PGRST_DB_URI: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_PREPARED_STATEMENTS: "false"
    networks:
      - coolify

  kong:
    image: kong:2.8.1
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
    volumes:
      - /root/supabase-configs/kong.yml:/var/lib/kong/kong.yml
    networks:
      - coolify

networks:
  coolify:
    external: true
