# Generated by Django 6.0.3 on 2026-03-23 05:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.TextField(default='enhances')),
                ('strength', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'connections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('is_mainline', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'connectors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
                ('stability_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('position_x', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('position_y', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_connectors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFocus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('focus_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_focus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Impulse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'impulses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.TextField(default='health')),
                ('frequency', models.TextField(default='daily')),
                ('color', models.TextField(blank=True, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
                ('node_type', models.TextField(choices=[('binary', 'Binary'), ('quantity', 'Quantity'), ('duration', 'Duration')], default='binary')),
                ('mass', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('stability_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('position_x', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('position_y', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('completion_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'node_connectors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profiles',
                'managed': False,
            },
        ),
    ]
