/**
 * Copyright (c) 2026 Web-Zhaba. All rights reserved.
 * Client-Side Physics Engine for Nodes Stability & Decay
 */

import type { Node, Impulse, CoreConnector, NodeConnector } from "@/types";

const BASE_PULSE_BUMP = 20.0;
const MAX_OVERDRIVE_MULTIPLIER = 1.5;
const DECAY_RATE_PER_DAY = 0.05; // 5% decay per day
const MAX_STABILITY = 100.0;

/**
 * Calculates the stability bump generated by a single impulse
 */
export function calculatePulseImpact(value: number, targetValue?: number | null): number {
  if (!targetValue || targetValue <= 0) {
    return BASE_PULSE_BUMP; // Default execution strength
  }

  let completionRatio = value / targetValue;
  if (completionRatio > MAX_OVERDRIVE_MULTIPLIER) {
    completionRatio = MAX_OVERDRIVE_MULTIPLIER;
  }

  return BASE_PULSE_BUMP * completionRatio;
}

/**
 * Recalculates stability score for a given node based on its impulses over the last 30 days
 */
export function recalculateNodeStability(node: Node, nodeImpulses: Impulse[]): number {
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - 30);
  cutoff.setHours(0, 0, 0, 0);

  // Filter impulses for the last 30 days and sort ascending by date
  const recent = nodeImpulses
    .filter((imp) => new Date(imp.completed_at) >= cutoff)
    .sort((a, b) => new Date(a.completed_at).getTime() - new Date(b.completed_at).getTime());

  if (recent.length === 0) {
    return 0.0;
  }

  let currentStability = 0.0;
  let lastDate = new Date(recent[0].completed_at);

  for (const pulse of recent) {
    const pulseDate = new Date(pulse.completed_at);
    const diffTime = pulseDate.getTime() - lastDate.getTime();
    const daysPassed = Math.floor(diffTime / (1000 * 60 * 60 * 24));

    if (daysPassed > 0) {
      const decayFactor = Math.pow(1.0 - DECAY_RATE_PER_DAY, daysPassed);
      currentStability *= decayFactor;
    }

    const impact = calculatePulseImpact(Number(pulse.value), node.target_value);
    currentStability += impact;

    if (currentStability > MAX_STABILITY) {
      currentStability = MAX_STABILITY;
    }

    lastDate = pulseDate;
  }

  // Decay stability from the last impulse to today
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const diffFromLast = today.getTime() - lastDate.getTime();
  const daysSinceLastPulse = Math.floor(diffFromLast / (1000 * 60 * 60 * 24));

  if (daysSinceLastPulse > 0) {
    const decayFactor = Math.pow(1.0 - DECAY_RATE_PER_DAY, daysSinceLastPulse);
    currentStability *= decayFactor;
  }

  return Math.round(currentStability * 100) / 100;
}

/**
 * Recalculates core stability as the average stability score of all linked nodes
 */
export function recalculateCoreStability(
  coreId: string,
  allNodes: Node[],
  coreConnectors: CoreConnector[],
  nodeConnectors: NodeConnector[]
): number {
  // Find connectors linked to this core
  const coreConnIds = coreConnectors
    .filter((cc) => cc.core_id === coreId)
    .map((cc) => cc.connector_id);

  if (coreConnIds.length === 0) {
    return 0.0;
  }

  // Find node IDs linked to those connectors
  const targetNodeIds = nodeConnectors
    .filter((nc) => coreConnIds.includes(nc.connector_id))
    .map((nc) => nc.node_id);

  const relatedNodes = allNodes.filter((n) => targetNodeIds.includes(n.id));

  if (relatedNodes.length === 0) {
    return 0.0;
  }

  const totalStability = relatedNodes.reduce((sum, n) => sum + (Number(n.stability_score) || 0), 0);
  return Math.round((totalStability / relatedNodes.length) * 100) / 100;
}
